### ISSUE TITLE
chatglm_qa在本地cpu运行，报错如下

### ISSUE THREAD

**Issue by hanyong-max** [IronSpiderMan/MachineLearningPractice#2]
Traceback (most recent call last):
  File "D:\MachineLearningPractice-main\chatglm_qa\chatglm_document_qa.py", line 69, in <module>
    db = store_chroma(documents, embeddings)
  File "D:\MachineLearningPractice-main\chatglm_qa\chatglm_document_qa.py", line 59, in store_chroma
    db = Chroma.from_documents(docs, embeddings, persist_directory=persist_directory)
  File "D:\Anaconda3\lib\site-packages\langchain_community\vectorstores\chroma.py", line 778, in from_documents
    return cls.from_texts(
  File "D:\Anaconda3\lib\site-packages\langchain_community\vectorstores\chroma.py", line 736, in from_texts
    chroma_collection.add_texts(
  File "D:\Anaconda3\lib\site-packages\langchain_community\vectorstores\chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "D:\Anaconda3\lib\site-packages\langchain_community\embeddings\huggingface.py", line 91, in embed_documents
    embeddings = self.client.encode(texts, **self.encode_kwargs)
  File "D:\Anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 153, in encode
    self.to(device)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "D:\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by hanyong-max** [comment]
主要是
db = Chroma.from_documents(docs, embeddings, persist_directory=persist_directory)
Chroma支持cpu吗？

**Comment by IronSpiderMan** [comment]
> 主要是 db = Chroma.from_documents(docs, embeddings, persist_directory=persist_directory) Chroma支持cpu吗？

支持的，这个情况是你cuda环境有问题，但是你又把内容上传到cuda了。可以创建Embedding的时候把设备设置成cpu。

**Comment by hanyong-max** [comment]
db = Chroma.from_documents(docs, embeddings, persist_directory=persist_directory, device="cpu")
是这样吗

**Comment by hanyong-max** [comment]
![image](https://github.com/IronSpiderMan/MachineLearningPractice/assets/54493615/a32a7670-4cff-403c-8adc-6bf0307f7417)
，cpu端运行后输入文字直接报错

**Comment by IronSpiderMan** [comment]
> ![image](https://private-user-images.githubusercontent.com/54493615/301760829-a32a7670-4cff-403c-8adc-6bf0307f7417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODY2MTAsIm5iZiI6MTcwNjg4NjMxMCwicGF0aCI6Ii81NDQ5MzYxNS8zMDE3NjA4MjktYTMyYTc2NzAtNGNmZi00MDNjLThhZGMtNmJmMDMwN2Y3NDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOWMyZTZmYjU4ZmQ3OGExNWRhNmYzMWUwYzQ4MjNjYzY3ZDNjZWQwOGMxMWUxNTgwNjVhN2I0M2FhMDkzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghaBa7Lb7ZHt-mOZSiLVeW9xGzMbIIzw9vGZCimLhFI) ，cpu端运行后输入文字直接报错

UI这里没有提供具体报错信息，可以截一下控制台的报错信息。

如果你的cuda环境有问题，你的glm也需要运行在cpu上，具体操作就是把api.py代码里面.cuda()删了。
